---
measurement_id:
  description: "The measurement ID to retrive from RIPE Atlas"
  type: "integer"
  required: true

rtt_tolerance:
  description: "The tolerance in ms for the drift of rtt"
  type: "integer"
  required: false
  default: 10

probes:
  description: "The probes to use when querying the measurement ID"
  type: "array"
  required: false
  items:
    type: "integer"
    required: true
