---
name: "rtt_drifted"
pack: "atlas"
description: "Triggered when the median rtt changed from a previously observed value."
enabled: true

trigger:
    type: "atlas.RTTMedianChanged"

action:
  ref: "twitter.update_status"
  parameters:
    status: "probe {{trigger.prb_id}} detected rtt median changed from {{trigger.old_hops_median}} to {{trigger.new_hops_median}}"
