---
name: "probes_disco_rules"
pack: "atlas"
description: "Rules for firing probes disco events"
enabled: true

trigger:
    type: "atlas.probes_disco"

# action:
#     ref: "core.local"
#     parameters:
#       cmd: "echo \"{{trigger.event}}\" >> /var/log/prb_evnts.log"

action:
  ref: "twitter.update_status"
  parameters:
    status: "{{trigger.event}}"