---
name: "unexpected_from_field"
pack: "atlas"
description: "Triggers when the at least one of the from fields of the probe attempts is different than the `dst_addr` field of the general result"
enabled: true

trigger:
    type: "atlas.FromFieldDifferentThanGeneral"

action:
  ref: "twitter.update_status"
  parameters:
    status: "probe {{trigger.prb_id}} expected from {{trigger.expected_from_field}} but detected the following extra from values: {{trigger.found_from_fields}}"
